plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xiaoyi.xinyuenovel'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xiaoyi.xinyuenovel'
        minSdk 23
        targetSdk 35
        versionCode 600
        versionName '6.0.0-multiai'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
